site_name: FynX
site_description: "Python Reactive State Management Library"
site_url: https://off-by-some.github.io/fynx/
docs_dir: ..
site_dir: ../../site

# Ignore template files during MkDocs processing
exclude_docs: |
  build/templates/**

nav:
  - Home: index.md
  - API Reference:
      - Overview: generation/markdown/api.md
      - Observables: generation/markdown/observables.md
      - Stores: generation/markdown/stores.md
      - Using @reactive: generation/markdown/using-reactive.md
      - Using @watch: generation/markdown/using-watch.md
      - Reference:
          - Observable Types:
              - Observable: generation/markdown/observable.md
              - ComputedObservable: generation/markdown/computed-observable.md
              - MergedObservable: generation/markdown/merged-observable.md
              - ConditionalObservable: generation/markdown/conditional-observable.md
              - Observable Descriptors: generation/markdown/observable-descriptors.md
              - Observable Operators: generation/markdown/observable-operators.md
          - Reactive Decorators:
              - "@computed": generation/markdown/computed-decorator.md
              - "@reactive": generation/markdown/reactive-decorator.md
              - "@watch": generation/markdown/watch-decorator.md
              - "Store & @observable": generation/markdown/store.md
  - Roadmap:
      - v1.0 Roadmap: specs/v1.0-roadmap.md

theme:
  name: material
  favicon: images/fynx_icon.svg
  logo: images/icon_350x350.png
  logo_text: FynX
  logo_text_align: center
  palette:
    - scheme: default
      primary: '#12172b'
      accent: '#12172b'
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#12172b'
      accent: '#12172b'
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_full_path: false
            show_category_heading: false
            show_labels: false
            show_root_members_full_path: false
            inherited_members: false
            show_object_full_path: false
            show_source: false
            show_bases: false
            separate_signature: true
            line_length: 80
            merge_init_into_class: true
            show_docstring_attributes: true
            show_docstring_classes: true
            show_docstring_functions: true
            show_docstring_modules: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/off-by-some/fynx
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fynx/

copyright: |
  &copy; 2024 Cassidy Bridges |
  <a href="#__consent">Change cookie settings</a>
