name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || (github.event.release.prerelease && 'testpypi' || 'pypi') }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.8.3

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project false

    - name: Install dependencies
      run: poetry install --with dev

    - name: Run tests
      run: poetry run pytest

    - name: Build package
      run: poetry build

    - name: Publish to TestPyPI
      if: env.POETRY_PYPI_TOKEN_TESTPYPI
      env:
        POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: poetry publish --repository testpypi

    - name: Publish to PyPI
      if: env.POETRY_PYPI_TOKEN_PYPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish
