site_name: FynX
site_description: "Python Reactive State Management Library"
site_url: https://off-by-some.github.io/fynx/
docs_dir: markdown
site_dir: ../../site

# Ignore template files during MkDocs processing
exclude_docs: |
  build/templates/**

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/off-by-some/fynx
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fynx/

nav:
  - Introduction:
      - Home: index.md
  - Tutorial:
      - Getting Started: tutorial/observables.md
      - Derived Observables: tutorial/derived-observables.md
      - Conditionals: tutorial/conditionals.md
      - Stores: tutorial/stores.md
      - Using @reactive: tutorial/using-reactive.md
  - API Reference:
      - Overview: reference/api.md
      - Observable Types:
          - Observable: reference/observable.md
          - Observable Operators: reference/observable-operators.md
          - ComputedObservable: reference/computed-observable.md
          - MergedObservable: reference/merged-observable.md
          - ConditionalObservable: reference/conditional-observable.md
          - Observable Descriptors: reference/observable-descriptors.md
      - Stores: reference/store.md
      - Reactive Decorators:
          - "@reactive": reference/reactive-decorator.md
  - Mathematical Foundations:
      - Mathematical Foundations: mathematical/mathematical-foundations.md
  - Roadmap:
      - v1.0 Roadmap: ../specs/v1.0-roadmap.md

theme:
  name: material
  favicon: assets/images/icon_350x350.png
  logo: assets/images/icon_350x350.png
  logo_text: FynX
  logo_text_align: center
  palette:
    - scheme: default
      primary: '#13162b'
      accent: '#13162b'
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#13162b'
      accent: '#13162b'
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    # - navigation.instant  # Temporarily disabled to test MathJax
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_full_path: false
            show_category_heading: false
            show_labels: false
            show_root_members_full_path: false
            inherited_members: false
            show_object_full_path: false
            show_source: false
            show_bases: false
            separate_signature: true
            line_length: 80
            merge_init_into_class: true
            show_docstring_attributes: true
            show_docstring_classes: true
            show_docstring_functions: true
            show_docstring_modules: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  Cassidy Bridges &copy; 2025
